### ISSUE TITLE
If no necesarioo

### ISSUE THREAD

**Issue by lunamendoza** [Edgar-LZ/Java_Course#13]
https://github.com/Edgar-LZ/Java_Course/blob/e1cb763ca1131e2ce7fdc08307692453ef2ee689/telegrama/src/telegrama/Telegrama.java#L14

Este if lo puedes agregar en la siguiente linea con una condicion que valide que no es un espacio.

**Comment by Edgar-LZ** [comment]
Se borró el if y se incluyó la validación en la siguiente línea.
